apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app2-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app2
  targetCPUUtilizationPercentage: 80
